{"name": "Проверяем ситуацию, когда не найден ни один пользователь", "status": "passed", "steps": [{"name": "Проверка статуса ответа", "status": "passed", "start": 1743349329492, "stop": 1743349329493}], "start": 1743349329085, "stop": 1743349329493, "uuid": "367a9cc1-838a-4e55-9b24-a12dc19328ab", "historyId": "9dd7ca180ba6cc6233c249293ae592d4", "testCaseId": "9dd7ca180ba6cc6233c249293ae592d4", "fullName": "tests.test_get_user_data#test_user_not_found", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_user_data"}, {"name": "host", "value": "Princess"}, {"name": "thread", "value": "23808-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_user_data"}]}